Support YoutacRandS-VA's open source work

# These are supported funding model platforms

github: [youtacrands-va, Youtac-Resources-and-Services]
patreon: patreon.com/user?u=107365027
open_collective: VINCENT10
custom: ["https://youtacrs.wordpress.com", "https://youtacrs8.wordpress.com"]

